demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='homepage'),
    #url(r'^add/$', views.add, name='add'),
    url(r'^new_add/(\d+)/(\d+)/$', views.add2, name='add2'),
    url(r'^delete/$', views.access_error,),
    url(r'^delete/(\w+)/(\w+)/$', views.hello_delete, name='ddd'),
    url(r'', include('myapp.urls')),
    url(r'', include('services.urls')),
    url(r'^userauth/', include('userauth.urls')),
]

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'myapp'
urlpatterns = [
    url(r'^hello2',views.hello_delete, name='home2'),
    url(r'^hello',views.hello_add, name='home'),
    url(r'^info/$', views.demo, name='info'),
    url(r'^demo/$', views.DemoShowView.as_view(), name='demo'),
    #url(r'^login', views.login, name='loginpage'),
    url(r'^blogindex/$', views.blogindex, name='blogindex'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='datearchives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category_archives'),
]

services/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'services'
urlpatterns = [
    url(r'^url/$',views.UrlView.as_view(), name='url'),
    url(r'^url/(?P<pk>[0-9]+)/$', views.UrlDetailView.as_view(), name='url_detail'),
    url(r'^url/environment/(?P<pk>[0-9]+)/$',views.Environment_typeView.as_view(), name='environment'),
    url(r'^elasticsearchinfo/$', views.ElasticsearchView.as_view(), name='elasticsearchinfo'),
    url(r'^search/$', views.search, name='search'),
]

userauth/urls.py
from django.conf.urls import url, include
#from django.contrib import admin
from . import views
#from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy

app_name = 'userauth'
urlpatterns = [
    #url(r'^login/$',views.user_login, name='login'),
    #url(r'',include('django.contrib.auth.urls')),
    
    # Django 1.11.0
    # login & logout
    #url(r'^login/$',login, name='login'),
    #url(r'^logout/$',logout, name='logout'),
    url('^login/$',auth_views.LoginView.as_view(template_name='userauth/login.html'), name='login'),
    url('^logout/$',auth_views.LogoutView.as_view(template_name='userauth/logged_out.html'), name='logout'),
    # dashboard
    url('^$',views.dashboard, name='dashboard'),
    # change password
    url('^password-change/$',auth_views.PasswordChangeView.as_view(template_name='userauth/password_change_form.html',
    															   success_url=reverse_lazy('userauth:password_change_done')), name='password_change'),
    url('^password-change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='userauth/password_change_done.html'),name='password_change_done'),
    # reset password & restore password urls
    # email address needs to match the user info
    url('^password-reset/$',auth_views.PasswordResetView.as_view(template_name='userauth/password_reset.html',
    															 email_template_name='userauth/password_reset_email.html', 
    															 subject_template_name='userauth/password_reset_subject.txt',
    															 success_url=reverse_lazy('userauth:password_reset_done')), name='password_reset'),
    url('^password-reset/done/$',auth_views.PasswordResetDoneView.as_view(template_name='userauth/password_reset_done.html'), name='password_reset_done'),
    url('^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.PasswordResetConfirmView.as_view(template_name='userauth/password_reset_confirm.html',
    																												 success_url=reverse_lazy('userauth:password_reset_complete')), name='password_reset_confirm'),
    url('^password-reset/complete/$',auth_views.PasswordResetCompleteView.as_view(template_name='userauth/password_reset_complete.html'), name='password_reset_complete'),
]

services/models.py
# -*- coding:UTF-8 -*-

from django.db import models
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Server_Type(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Server_URLs(models.Model):
	app_name = models.CharField(max_length=255)
	url = models.URLField(default="http://")
	description = models.CharField(max_length=255, blank=True, verbose_name='备注')
	required_database = models.TextField(blank=True, verbose_name='连接的数据库')
	required_api = models.TextField(blank=True, verbose_name='API调用')

	# 逻辑：
	# 规定一个内容只能对应一个环境，但是一个环境下可以有多个服务，所以使用 ForeignKey，服务和环境的关系为一对多的关联关系
	servertype = models.ForeignKey(Server_Type)
	def __str__(self):
		return self.app_name

	def get_absolute_url(self):
		return reverse('services:url_detail', kwargs={'pk': self.pk})

	class Meta:
		ordering = ['servertype', 'app_name']
		verbose_name = 'URL'
		verbose_name_plural = 'URL'

@python_2_unicode_compatible
class Elasticsearch_Node(models.Model):
	IP_Address = models.GenericIPAddressField()
	Node_Name = models.CharField(max_length=255)

	def __str__(self):
		return self.Node_Name

services/views.py
import markdown
import logging
from django.shortcuts import render,get_object_or_404
from django.shortcuts import HttpResponse
from services import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
from elasticsearch import Elasticsearch

# Create your views here.

# logging
logger = logging.getLogger(__name__)

'''
@login_required
def url(request):
	context_url = {}
	context_url['section'] = 'url' 
	# 因为 models 文件定义了 Meta ，所以无需指定 order_by
	#context_url["app_url"] = models.Server_URLs.objects.all().order_by('servertype')
	context_url["url_list"] = models.Server_URLs.objects.all()
	return render(request, 'services/url.html', context_url)
'''

class PaginationData:
	def pagination_data(self, paginator, page, is_paginated):
		# 如果没有分页，则无需显示分页
		# 不用任何分页导航条的数据，因此返回一个空的字典
		if is_paginated == False:
			return {}

		# 当前页左边连续的页码号，初始值为空
		left = []

		# 当前页右边连续的页码号，初始值为空
		right = []

		# 标示第 1 页页码后是否需要显示省略号
		left_has_more = False

		# 标示z最后一页页码前是否需要显示省略号
		right_has_more = False

		# 标示是否需要显示第 1 页或最后一页的页码号
		# 如果当前页左边的连续页码号中含有第 1 页或最后一页的页码号，则无需再显示
		# 默认初始值为False
		first = False
		last = False

		# 标识是否需要上一页和下一页
		# 默认为True
		has_previous_page = True
		has_next_page = True

		# 获得用户当前请求的页码号
		current_number = page.number

		# 获得分页后的总页数
		total_number = paginator.num_pages

		# 获得整个分页的页码列表，比如分了两页，则为range(1,3)
		page_range = paginator.page_range

		if current_number == 1:
			# 判断是否有前一页
			has_previous_page = page.has_previous

			# 如果当前页为第一页，则当前页的左边不需要数据
			# 此时只要获得当前页右边的连续页码号
			# 这里将获得当前页码后连续两个页码
			right = page_range[current_number:current_number + 2]

			# 如果最右边的页码号比总页数减去1还要小
			# 说明最右边的页码号和最后一页的页码号之间还有其他页码，因此需要显示省略号
			if right[-1] < total_number - 1:
				right_has_more = True

			# 如果最右边的页码号比总页数要小
			# 说明当前页右边的连续页码号中不包含最后一页，所以需要显示最后一页的页码号
			if right[-1] < total_number:
				last = True

		elif current_number == total_number:
			# 判断是否有下一页
			has_next_page = page.has_next
			# 如果请求最后一页，则当前页左边右边不再需要数据
			# 此时需要获得当前页左边的连续页码号
			left =  page_range[(current_number - 3) if (current_number - 3) > 0 else 0:current_number -1]

			# 如果最左边的页码号比2还大，说明和第 1 页之间有其他页码，需要显示省略号
			if left[0] > 2:
				left_has_more = True
			# 如果最左边的页码号比1大，说明不包含第 1 页，需要显示第 1 页的页码号
			if left[0] > 1:
				first = True

		else:
			# 如果请求的既不是第 1 页也不是最后一页，则需要获得左右两边的连续页码号
			# 同样还是获取当前页码前后的连续两个页面
			left =  page_range[(current_number - 3) if (current_number - 3) > 0 else 0:current_number -1]
			right = page_range[current_number:current_number + 2]

			# 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_number - 1:
				right_has_more = True
			if right[-1] < total_number:
				last = True

			# 是否需要显示第 1 页和第 1 页后的省略号				
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
			'has_next_page': has_next_page,
			'has_previous_page': has_previous_page,
		}

		return data


class UrlView(LoginRequiredMixin, ListView, PaginationData):

	model = models.Server_URLs
	template_name = "services/url.html"
	context_object_name = "url_list"
	paginate_by = 15

	def get_context_data(self, **kwargs):
		logger.info("进入UrlView查询")
		context_url = super(UrlView, self).get_context_data(**kwargs)
		context_url['section'] = 'url'
		context_url['error_msg'] = ''

		# 生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量
		# 由于 context_url 是一个字典，所以调用 get 方法从中取出某个键对应的值
		paginator = context_url.get('paginator')
		page = context_url.get('page_obj')
		is_paginated = context_url.get('is_paginated')

		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context_url.update(pagination_data)
		logger.info("查询UrlView完成")
		return context_url

'''
# 以下方法已经不再使用，修改为通用视图方法
def environment_type(request, pk):
	context_environment = {}
	context_environment['section'] = 'url'
	type = get_object_or_404(models.Server_Type, pk=pk)
	context_environment["url_list"] = models.Server_URLs.objects.filter(servertype=type)
	return render(request, 'services/url.html', context_environment)
'''

class Environment_typeView(LoginRequiredMixin, ListView, PaginationData):

	model = models.Server_URLs
	template_name = "services/url.html"
	context_object_name = "url_list"
	paginate_by = 15

	def get_queryset(self):
		type = get_object_or_404(models.Server_Type, pk=self.kwargs.get('pk'))
		return super(Environment_typeView, self).get_queryset().filter(servertype=type)

	def get_context_data(self, **kwargs):
		context_environment = super(Environment_typeView, self).get_context_data(**kwargs)
		context_environment['section'] = 'url'
		context_environment['error_msg'] = ''

		paginator = context_environment.get('paginator')
		page = context_environment.get('page_obj')
		is_paginated = context_environment.get('is_paginated')

		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context_environment.update(pagination_data)		
		return context_environment

@login_required
def url_detail(request, pk):
	context_url_detail = {}
	context_url_detail['section'] = 'url'
	context_url_detail['url'] = get_object_or_404(models.Server_URLs, pk=pk)
	context_url_detail['url'].required_database =  markdown.markdown(context_url_detail['url'].required_database,
														extensions = [
															'markdown.extensions.extra',
															'markdown.extensions.codehilite',
															'markdown.extensions.toc',
															]
														)
	context_url_detail['url'].required_api =  markdown.markdown(context_url_detail['url'].required_api,
														extensions = [
															'markdown.extensions.extra',
															'markdown.extensions.codehilite',
															'markdown.extensions.toc',
															]
														)
	return render(request, 'services/url_detail.html', context_url_detail)

class UrlDetailView(LoginRequiredMixin, DetailView):

	model = models.Server_URLs
	template_name = "services/url_detail.html"
	context_object_name = "url"

	def get_object(self, queryset=None):
		url = super(UrlDetailView, self).get_object(queryset=queryset)
		url.required_database = markdown.markdown(url.required_database,
													extensions = [
														'markdown.extensions.extra',
														'markdown.extensions.codehilite',
														'markdown.extensions.toc',
														]
													)
		url.required_api = markdown.markdown(url.required_api,
													extensions = [
														'markdown.extensions.extra',
														'markdown.extensions.codehilite',
														'markdown.extensions.toc',
														]
													)
		url.temp = "testinfo"
		return url

	def get_context_data(self, **kwargs):
		context_url_detail = super(UrlDetailView, self).get_context_data(**kwargs)
		context_url_detail['section'] = 'url'
		return context_url_detail

@login_required
def search(request):
	q = request.GET.get('q')
	context_search = {}
	context_search['section'] = 'url'
	context_search['error_msg'] = ''

	if not q:
		context_search[error_msg] = '请输入关键词'
		return render(request, 'services/url.html', context_search)

	# icontains为不区分大小写，contains则区分大小写
	context_search['url_list'] = models.Server_URLs.objects.filter(Q(url__icontains=q) | Q(required_api__icontains=q))
	return render(request, 'services/url.html', context_search)

class ElasticsearchView(LoginRequiredMixin, ListView, PaginationData):

	model = models.Elasticsearch_Node
	template_name = "services/elasticsearch.html"
	#context_object_name = "ela"
	paginate_by = 15

	def get_context_data(self, **kwargs):
		context_elasticsearch = super(ElasticsearchView, self).get_context_data(**kwargs)
		context_elasticsearch['section'] = 'url'
		context_elasticsearch['error_msg'] = ''
		#context_elasticsearch['node_ip'] = models.Elasticsearch_Node.objects.all().values("IP_Address")
		#context_elasticsearch['node_name'] = models.Elasticsearch_Node.objects.all().values("Node_Name")
		logger.info("ElasticsearchView-logging-1")
		node_ip_list = models.Elasticsearch_Node.objects.all().values("IP_Address")
		logger.info(node_ip_list)
		logger.info("ElasticsearchView-logging-2")
		node_name_list = models.Elasticsearch_Node.objects.all().values("Node_Name")
		logger.info(node_name_list)
		context_elasticsearch['nodeinfo'] = node_ip_list
		node_ip_list_length = len(node_ip_list)
		node_name_list_length = len(node_name_list)

		if node_ip_list_length == node_name_list_length:
			logger.info("data match")
			i = 0
			while i < node_ip_list_length:
				context_elasticsearch['nodeinfo'][i].update(node_name_list[i])
				i += 1
			logger.info("increase data complete")
		else:
			logger.info("data match failed")

		logger.info("ElasticsearchView-logging-3")
		logger.info(context_elasticsearch['nodeinfo'])

		
		for k in context_elasticsearch['nodeinfo']:
			elasticsearch_host = k['IP_Address']
			elasticsearch_node_name = k['Node_Name']
			k.update(self.Elasticsearchinfo_Collect(elasticsearch_host, elasticsearch_node_name))
		
		# test
		#context_elasticsearch['temp'] = self.Elasticsearchinfo_Collect("10.181.57.57", "10.181.57.57")
		#logger.info("ElasticsearchView-logging-4")
		#logger.info(context_elasticsearch['temp'])

		logger.info("ElasticsearchView-logging-5")
		logger.info(context_elasticsearch['nodeinfo'])
		return context_elasticsearch

	def Elasticsearchinfo_Collect(self, elasticsearch_host, elasticsearch_node_name, elasticsearch_port="9200"):

		# 配置host和port
		ela_host = Elasticsearch([{'host': elasticsearch_host, 'port': elasticsearch_port}])

		# 获取cluster的health信息
		ela_cluster_health = ela_host.cluster.health()
		
		# 获取nodes的info信息
		ela_nodes_simple_info = ela_host.nodes.info(node_id=elasticsearch_node_name)
		# 获取nodes对应的uid
		ela_nodes_uid = "".join(list(ela_nodes_simple_info["nodes"].keys()))
		

templates/services/elasticsearch.html
{% extends "base.html" %}

{% block style %}
<style type="text/css">
/* Hide for mobile, show later */
.sidebar {
  display: none;
}
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 51px;
    bottom: 0;
    right: 0;
    z-index: 1000;
    display: block;
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
    background-color: #f5f5f5;
    border-left: 3px solid #eee;
  }
}
</style>
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container" style="margin-top: -30px; margin-left: -10px;">
	<main class="col-md-11">
		<!-- <div class="widget widget-recent-posts"> -->
			<div class="table-responsive">
				<table class="table table-striped">
        			<thead>
        		    	<tr>
                            <th>IP</th>
                            <th>CPU</th>
                            <th>Disk</th>
                            <th>Query_Para</th>
                            <th>Fetch_Para</th>
                            <th>heap_used_percent</th>
                            <th>JDK</th>
                            <th>Status</th>
        		        </tr>
        		    </thead>
        		    <tbody>
                        {% for ela in nodeinfo %}
        		    	<tr>
        		    		<td>{{ ela.IP_Address }}</td>
        		    		<td style="color: #008B45;">{{ ela.elasticsearch_node_info_cpu.cpu.percent }}%</td>
                            <td>{{ ela.elasticsearch_node_info_fs.total.available_in_bytes }}G / {{ ela.elasticsearch_node_info_fs.total.total_in_bytes }}G</td>
                            <td>{{ ela.elasticsearch_node_info_indices.search.query_latency }} ms ({{ ela.elasticsearch_node_info_indices.search.query_time_in_millis }} / {{ ela.elasticsearch_node_info_indices.search.query_total }})</td>
                            <td>{{ ela.elasticsearch_node_info_indices.search.fetch_latency }} ms ({{ ela.elasticsearch_node_info_indices.search.fetch_time_in_millis }} / {{ ela.elasticsearch_node_info_indices.search.fetch_total }})</td>
                            <td style="color: #483D8B;">{{ ela.elasticsearch_node_info_jvm.mem.heap_used_percent }}%</td>
                            <td>{{ ela.elasticsearch_node_info_jvm.others.version }}</td>
                            {% if ela.elasticsearch_cluster_health.status == "green" %}
                            <td style="background-color: #C1FFC1;">UP</td>
                            {% elif ela.elasticsearch_cluster_health.status == "yellow" %}
                            <td style="background-color: #fef4a4;">Warn</td>
                            {% elif ela.elasticsearch_cluster_health.status == "red" %}
                            <td style="background-color: #CD5C5C;">Error</td>
                            {% endif %}
        		    	</tr>
                        {% endfor %}
        		    </tbody>
        		</table>
    		</div>
    		{% if error_msg %}
    		<p>{{ error_msg }}</p>
    		{% endif %}
            <p class="lead">{{ nodeinfo }}</p>
    		{% if is_paginated == True %}
    		<ul class="pager">
    			{% if has_previous_page == True %}
    			<li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    			{% endif %}
    			{% if first == True %}
    			<li><a href="?page=1">1</a></li>
    			{% endif %}
    			{% if left %}
    				{% if left_has_more == True %}
    				<li><span>...</span></li>
    				{% endif %}
    				{% for i in left %}
    				<li><a href="?page={{ i }}">{{ i }}</a></li>
    				{% endfor %}
    			{% endif %}
    			<!-- 显示当前页面信息 -->
    			<!-- <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span> -->
    			<li><a href="?page={{ page_obj.number }}" style="color: #fff; background-color: #337ab7;">{{ page_obj.number }}</a></li>
    			{% if right %}
    			    {% for i in right %}
    				<li><a href="?page={{ i }}">{{ i }}</a></li>
    				{% endfor %}
    				{% if right_has_more == True %}
    				<li><span>...</span></li>
    				{% endif %}
    			{% endif %}
    			{% if last == True %}
    			<li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
    			{% endif %}
    			{% if has_next_page == True %}
    			<li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    			{% endif %}
    		</ul>
    		{% else %}
    		<ul class="pager">
    			<li>End</li>
    		</ul>
    		{% endif %}
		<!-- </div> -->
	</main>
	{% load environment %}
	<aside class="col-md-2 sidebar">
		<div class="widget widget-recent-posts" style="margin-left: -20px; margin-top: 0px;">
			<div class="widget-title">应用环境</div>
			<!-- <hr style="background-color: #aaa; height: 1px; width: 120%; margin-top: -10px"> -->
			{% get_environment_type as environment_list %}
			<ul>
				<li><a href="{% url 'services:url' %}">所有环境</a></li>
				{% for type in environment_list %}
				<li><a href="{% url 'services:environment' type.pk %}">{{ type.name }}</a></li>
				{% empty %}
				<li>暂无分类!</li>
				{% endfor %}
			</ul>
            <ul style="margin-top: 20px;">
                <li><a href="{% url 'services:elasticsearchinfo' %}">elasticsearchinfo</a></li>
            </ul>
		</div>
	</aside>
</div>
{% endblock %}

templates/services/url.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container" style="margin-top: -30px">
	<main class="col-md-8">
		<div class="widget widget-recent-posts">
			{% for url in url_list %}
			<ul>
				<li>{{ url.servertype }} {{url.app_name}} <a href="#">{{ url.url }}</a></li>
			</ul>
			{% endfor %}
		</div>
	</main>
	{% load environment %}
	<aside class="col-md-4">	
		<div class="widget widget-recent-posts">
			<div class="widget-title">应用环境</div>
			{% get_environment_type as environment_list %}
			<ul>
				{% for type in environment_list %}
				<li><a href="{% url 'services:environment' type.pk %}">{{ type.name }}</a></li>
				{% empty %}
				<li>暂无分类!</li>
				{% endfor %}
			</ul>
		</div>
	</aside>
</div>
{% endblock %}

templates/services/url_detail.html
{% extends "base.html" %}

{% block style %}
<style type="text/css">
/* Hide for mobile, show later */
.sidebar {
  display: none;
}
@media (min-width: 768px) {
  .sidebar {
    position: fixed;
    top: 51px;
    bottom: 0;
    right: 0;
    z-index: 1000;
    display: block;
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
    background-color: #f5f5f5;
    border-left: 3px solid #eee;
  }
}
</style>
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container" style="margin-top: -30px; margin-left: -10px;">
	<main class="col-md-11">
        <article class="url-{{ url.pk }}">
            <div class="page-header"><h1>Databases</h1></div>
            <p>{{ url.required_database|safe }}</p>
            <div class="page-header"><h1>API</h1></div>
            <p>{{ url.required_api|safe }}</p>
            <hr style="background-color: #eee; height: 1px; width: 100%">
            <div class="read-more cl-effect-14">
                <a href="{% url 'services:url' %}" class="more-link">返回</a>
            </div>
        </article>
	</main>
	{% load environment %}
	<aside class="col-md-2 sidebar">
		<div class="widget widget-recent-posts" style="margin-left: -20px; margin-top: 0px;">
			<div class="widget-title">应用环境</div>
			{% get_environment_type as environment_list %}
			<ul>
                <li><a href="{% url 'services:url' %}">所有环境</a></li>
				{% for type in environment_list %}
				<li><a href="{% url 'services:environment' type.pk %}">{{ type.name }}</a></li>
				{% empty %}
				<li>暂无分类!</li>
				{% endfor %}
			</ul>
            <ul style="margin-top: 20px;">
                <li><a href="{% url 'services:elasticsearchinfo' %}">elasticsearchinfo</a></li>
            </ul>
		</div>
	</aside>
</div>
{% endblock %}