demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='homepage'),
    #url(r'^add/$', views.add, name='add'),
    url(r'^new_add/(\d+)/(\d+)/$', views.add2, name='add2'),
    url(r'^delete/$', views.access_error,),
    url(r'^delete/(\w+)/(\w+)/$', views.hello_delete, name='ddd'),
    url(r'', include('myapp.urls')),
    url(r'', include('services.urls')),
    url(r'^userauth/', include('userauth.urls')),
]

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'myapp'
urlpatterns = [
    url(r'^hello2',views.hello_delete, name='home2'),
    url(r'^hello',views.hello_add, name='home'),
    url(r'^info/$', views.demo, name='info'),
    url(r'^demo/$', views.DemoShowView.as_view(), name='demo'),
    #url(r'^login', views.login, name='loginpage'),
    url(r'^blogindex/$', views.blogindex, name='blogindex'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='datearchives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category_archives'),
]

services/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'services'
urlpatterns = [
    url(r'^url/$',views.UrlView.as_view(), name='url'),
    url(r'^url/(?P<pk>[0-9]+)/$', views.UrlDetailView.as_view(), name='url_detail'),
    url(r'^url/environment/(?P<pk>[0-9]+)/$',views.Environment_typeView.as_view(), name='environment'),
    url(r'^elasticsearchinfo/$', views.ElasticsearchView.as_view(), name='elasticsearchinfo'),
    url(r'^search/$', views.search, name='search'),
]

myapp/models.py
# -*- coding:UTF-8 -*-

# 因为注释含有中文，所以需要编码声明coding:UTF-8
# 所有中文段落，符号也均为中文样式。反之，英文段落，符号为英文样式。
# 修改完需要通过命令创建数据库的表，如下：
# python manage.py makemigrations
# python manage.py migrate

# django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

# Create your models here.

# 兼容python2，使python2.x 也像 python3 那个处理 unicode 字符，以便有更好地兼容性。
@python_2_unicode_compatible
# models.Model为固定写法，用法具体需要参考github上django的源码
class UserInfo(models.Model):
	#创建两个字段，最大长度32，类型是char
	user = models.CharField(max_length=32)
	pwd = models.CharField(max_length=32)
	def __str__(self):
		return self.user

@python_2_unicode_compatible
class TestInfo(models.Model):
	user = models.CharField(max_length=32)
	pwd = models.CharField(max_length=32)

@python_2_unicode_compatible
class Article(models.Model):
	title = models.CharField(u'标题', max_length=256)
	# 允许为空
	content = models.TextField(u'内容', null=True, blank=True)
	pub_date = models.DateTimeField(u'发表时间', auto_now_add=True, editable=True)
	update_time = models.DateTimeField(u'更新时间', auto_now=True, null=True)
	def __str__(self):
		return self.title
		

########################### Blog Part ###########################
# 定义模型，我们这里需要 3个表格：文章（Article_Blog）、分类（Category）以及标签（tag）
@python_2_unicode_compatible
class Category(models.Model):
	# Django 要求模型必须继承 models.Model 类。
	# Category 只需要一个简单的分类名 name 就可以了。
	# CharField 指定了分类名 name 的市局类型为字符型，其余类型需要参考源码或官方文档。
	# max_length 指定字段最大长度，超过这个长度的分类名就不能被存入数据库。
	# 当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
	# Django 内置的全部类型可查看文档：
	# https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Tag(models.Model):
	# 标签 Tag 也需要一个 name
	# 在这里把长度设置为 100
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Article_Blog(models.Model):
	# 文章标题, 这里给到的长度 max_length 为 256
	title = models.CharField(max_length=256)

	# 文章正文，定义字段为TextField
	# 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是大段文本，因此使用 TextField 来存储大段文本。
	content = models.TextField()

	# 定义创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()

	# 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则报错
	# 指定 blank=True 参数值后可以允许为空
	excerpt = models.CharField(max_length=256, blank=True)
	
	# 关联分类和标签，之前已经完成定义。在这里，我们需要将文章对应的数据库表和分类、标签对应的数据库表关联起来。
	# 逻辑：
	# 规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以使用 ForeignKey，文章和分类的关系为一对多的关联关系。
	# 对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以使用 ManyToManyField，表明两者是多对多的关联关系。
	# 同时规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
	# 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
	# https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
	category = models.ForeignKey(Category)
	tags = models.ManyToManyField(Tag, blank=True)

	# 文章作者，这里 User 是从 jango.contrib.auth.models 导入的。
	# django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
	# 这里我们通过 ForeignKey 把文章和 User 关联了起来。
	# 逻辑：规定一篇文章只能有一个作者，而一个作者可以有多篇文章，所以为一对多的关联关系
	author = models.ForeignKey(User)

	def __str__(self):
		return self.title

	# 自定义 get_absolute_url 方法
	# 记得从 django.urls 中导入 reverse 函数
	def get_absolute_url(self):
		return reverse('myapp:detail', kwargs={'pk': self.pk})

########################### Blog Part end ###########################

########################### Blog comments ###########################



######################## Blog comments end ##########################

services/views.py
import markdown
import logging
from django.shortcuts import render,get_object_or_404
from django.shortcuts import HttpResponse
from services import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
from elasticsearch import Elasticsearch

# Create your views here.

# logging
logger = logging.getLogger(__name__)

'''
@login_required
def url(request):
	context_url = {}
	context_url['section'] = 'url' 
	# 因为 models 文件定义了 Meta ，所以无需指定 order_by
	#context_url["app_url"] = models.Server_URLs.objects.all().order_by('servertype')
	context_url["url_list"] = models.Server_URLs.objects.all()
	return render(request, 'services/url.html', context_url)
'''

class PaginationData:
	def pagination_data(self, paginator, page, is_paginated):
		# 如果没有分页，则无需显示分页
		# 不用任何分页导航条的数据，因此返回一个空的字典
		if is_paginated == False:
			return {}

		# 当前页左边连续的页码号，初始值为空
		left = []

		# 当前页右边连续的页码号，初始值为空
		right = []

		# 标示第 1 页页码后是否需要显示省略号
		left_has_more = False

		# 标示z最后一页页码前是否需要显示省略号
		right_has_more = False

		# 标示是否需要显示第 1 页或最后一页的页码号
		# 如果当前页左边的连续页码号中含有第 1 页或最后一页的页码号，则无需再显示
		# 默认初始值为False
		first = False
		last = False

		# 标识是否需要上一页和下一页
		# 默认为True
		has_previous_page = True
		has_next_page = True

		# 获得用户当前请求的页码号
		current_number = page.number

		# 获得分页后的总页数
		total_number = paginator.num_pages

		# 获得整个分页的页码列表，比如分了两页，则为range(1,3)
		page_range = paginator.page_range

		if current_number == 1:
			# 判断是否有前一页
			has_previous_page = page.has_previous

			# 如果当前页为第一页，则当前页的左边不需要数据
			# 此时只要获得当前页右边的连续页码号
			# 这里将获得当前页码后连续两个页码
			right = page_range[current_number:current_number + 2]

			# 如果最右边的页码号比总页数减去1还要小
			# 说明最右边的页码号和最后一页的页码号之间还有其他页码，因此需要显示省略号
			if right[-1] < total_number - 1:
				right_has_more = True

			# 如果最右边的页码号比总页数要小
			# 说明当前页右边的连续页码号中不包含最后一页，所以需要显示最后一页的页码号
			if right[-1] < total_number:
				last = True

		elif current_number == total_number:
			# 判断是否有下一页
			has_next_page = page.has_next
			# 如果请求最后一页，则当前页左边右边不再需要数据
			# 此时需要获得当前页左边的连续页码号
			left =  page_range[(current_number - 3) if (current_number - 3) > 0 else 0:current_number -1]

			# 如果最左边的页码号比2还大，说明和第 1 页之间有其他页码，需要显示省略号
			if left[0] > 2:
				left_has_more = True
			# 如果最左边的页码号比1大，说明不包含第 1 页，需要显示第 1 页的页码号
			if left[0] > 1:
				first = True

		else:
			# 如果请求的既不是第 1 页也不是最后一页，则需要获得左右两边的连续页码号
			# 同样还是获取当前页码前后的连续两个页面
			left =  page_range[(current_number - 3) if (current_number - 3) > 0 else 0:current_number -1]
			right = page_range[current_number:current_number + 2]

			# 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_number - 1:
				right_has_more = True
			if right[-1] < total_number:
				last = True

			# 是否需要显示第 1 页和第 1 页后的省略号				
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
			'has_next_page': has_next_page,
			'has_previous_page': has_previous_page,
		}

		return data


class UrlView(LoginRequiredMixin, ListView, PaginationData):

	model = models.Server_URLs
	template_name = "services/url.html"
	context_object_name = "url_list"
	paginate_by = 15

	def get_context_data(self, **kwargs):
		logger.info("进入UrlView查询")
		context_url = super(UrlView, self).get_context_data(**kwargs)
		context_url['section'] = 'url'
		context_url['error_msg'] = ''

		# 生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量
		# 由于 context_url 是一个字典，所以调用 get 方法从中取出某个键对应的值
		paginator = context_url.get('paginator')
		page = context_url.get('page_obj')
		is_paginated = context_url.get('is_paginated')

		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context_url.update(pagination_data)
		logger.info("查询UrlView完成")
		return context_url

'''
# 以下方法已经不再使用，修改为通用视图方法
def environment_type(request, pk):
	context_environment = {}
	context_environment['section'] = 'url'
	type = get_object_or_404(models.Server_Type, pk=pk)
	context_environment["url_list"] = models.Server_URLs.objects.filter(servertype=type)
	return render(request, 'services/url.html', context_environment)
'''

class Environment_typeView(LoginRequiredMixin, ListView, PaginationData):

	model = models.Server_URLs
	template_name = "services/url.html"
	context_object_name = "url_list"
	paginate_by = 15

	def get_queryset(self):
		type = get_object_or_404(models.Server_Type, pk=self.kwargs.get('pk'))
		return super(Environment_typeView, self).get_queryset().filter(servertype=type)

	def get_context_data(self, **kwargs):
		context_environment = super(Environment_typeView, self).get_context_data(**kwargs)
		context_environment['section'] = 'url'
		context_environment['error_msg'] = ''

		paginator = context_environment.get('paginator')
		page = context_environment.get('page_obj')
		is_paginated = context_environment.get('is_paginated')

		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context_environment.update(pagination_data)		
		return context_environment

@login_required
def url_detail(request, pk):
	context_url_detail = {}
	context_url_detail['section'] = 'url'
	context_url_detail['url'] = get_object_or_404(models.Server_URLs, pk=pk)
	context_url_detail['url'].required_database =  markdown.markdown(context_url_detail['url'].required_database,
														extensions = [
															'markdown.extensions.extra',
															'markdown.extensions.codehilite',
															'markdown.extensions.toc',
															]
														)
	context_url_detail['url'].required_api =  markdown.markdown(context_url_detail['url'].required_api,
														extensions = [
															'markdown.extensions.extra',
															'markdown.extensions.codehilite',
															'markdown.extensions.toc',
															]
														)
	return render(request, 'services/url_detail.html', context_url_detail)

class UrlDetailView(LoginRequiredMixin, DetailView):

	model = models.Server_URLs
	template_name = "services/url_detail.html"
	context_object_name = "url"

	def get_object(self, queryset=None):
		url = super(UrlDetailView, self).get_object(queryset=queryset)
		url.required_database = markdown.markdown(url.required_database,
													extensions = [
														'markdown.extensions.extra',
														'markdown.extensions.codehilite',
														'markdown.extensions.toc',
														]
													)
		url.required_api = markdown.markdown(url.required_api,
													extensions = [
														'markdown.extensions.extra',
														'markdown.extensions.codehilite',
														'markdown.extensions.toc',
														]
													)
		url.temp = "testinfo"
		return url

	def get_context_data(self, **kwargs):
		context_url_detail = super(UrlDetailView, self).get_context_data(**kwargs)
		context_url_detail['section'] = 'url'
		return context_url_detail

@login_required
def search(request):
	q = request.GET.get('q')
	context_search = {}
	context_search['section'] = 'url'
	context_search['error_msg'] = ''

	if not q:
		context_search[error_msg] = '请输入关键词'
		return render(request, 'services/url.html', context_search)

	# icontains为不区分大小写，contains则区分大小写
	context_search['url_list'] = models.Server_URLs.objects.filter(Q(url__icontains=q) | Q(required_api__icontains=q))
	return render(request, 'services/url.html', context_search)

class ElasticsearchView(LoginRequiredMixin, ListView, PaginationData):

	model = models.Elasticsearch_Node
	template_name = "services/elasticsearch.html"
	#context_object_name = "ela"
	paginate_by = 15

	def get_context_data(self, **kwargs):
		context_elasticsearch = super(ElasticsearchView, self).get_context_data(**kwargs)
		context_elasticsearch['section'] = 'url'
		context_elasticsearch['error_msg'] = ''
		#context_elasticsearch['node_ip'] = models.Elasticsearch_Node.objects.all().values("IP_Address")
		#context_elasticsearch['node_name'] = models.Elasticsearch_Node.objects.all().values("Node_Name")
		logger.info("ElasticsearchView-logging-1")
		node_ip_list = models.Elasticsearch_Node.objects.all().values("IP_Address")
		logger.info(node_ip_list)
		logger.info("ElasticsearchView-logging-2")
		node_name_list = models.Elasticsearch_Node.objects.all().values("Node_Name")
		logger.info(node_name_list)
		context_elasticsearch['nodeinfo'] = node_ip_list
		node_ip_list_length = len(node_ip_list)
		node_name_list_length = len(node_name_list)

		if node_ip_list_length == node_name_list_length:
			logger.info("data match")
			i = 0
			while i < node_ip_list_length:
				context_elasticsearch['nodeinfo'][i].update(node_name_list[i])
				i += 1
			logger.info("increase data complete")
		else:
			logger.info("data match failed")

		logger.info("ElasticsearchView-logging-3")
		logger.info(context_elasticsearch['nodeinfo'])

		
		for k in context_elasticsearch['nodeinfo']:
			elasticsearch_host = k['IP_Address']
			elasticsearch_node_name = k['Node_Name']
			k.update(self.Elasticsearchinfo_Collect(elasticsearch_host, elasticsearch_node_name))
		
		# test
		#context_elasticsearch['temp'] = self.Elasticsearchinfo_Collect("10.181.57.57", "10.181.57.57")
		#logger.info("ElasticsearchView-logging-4")
		#logger.info(context_elasticsearch['temp'])

		logger.info("ElasticsearchView-logging-5")
		logger.info(context_elasticsearch['nodeinfo'])
		return context_elasticsearch

	def Elasticsearchinfo_Collect(self, elasticsearch_host, elasticsearch_node_name, elasticsearch_port="9200"):

		# 配置host和port
		ela_host = Elasticsearch([{'host': elasticsearch_host, 'port': elasticsearch_port}])

		# 获取cluster的health信息
		ela_cluster_health = ela_host.cluster.health()
		
		# 获取nodes的info信息
		ela_nodes_simple_info = ela_host.nodes.info(node_id=elasticsearch_node_name)
		# 获取nodes对应的uid
		ela_nodes_uid = "".join(list(ela_nodes_simple_info["nodes"].keys()))
		

templates/blog/detail.html
{% extends "base.html" %}

{% block style %}
<style type="text/css">
	/* body {color: #EE0000;} */
	a {
    	color: #464547;
	}

	a:hover, a:focus {
		text-decoration: none;
		color: #000;
}
</style>
{% endblock %}

{% block nav %}
<!-- <li><a href="{% url 'myapp:home' %}">Home</a></li>
<li><a href="{% url 'services:url' %}">URL</a></li>
<li  class="active"><a href="{% url 'myapp:blogindex' %}">Blog</a></li> -->
{% endblock %}

{% block body %}
<div class="container" style="margin-top: -35px">
	<main class="col-md-8">
<!-- 从数据库中读取对应的内容，应用到每个地方 -->
		<article class="post-{{ post.pk }}">
			<header>
				<div class="entry-title">
					{{ post.title }}
				</div>
				<div class="entry-meta">
					<span class="post-category"><a href="#">{{ post.category.name }}</a></span>
					<span class="post-date"><a href="#"><time datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
					<span class="post-author"><a href="#">{{ post.author }}</a></span>
					<!-- <span class="comments-link"><a href="#">分类显示demo</a></span> -->
				</div>
			</header>
			<div class="entry-content clearfix">
				<p>{{ post.content|safe }}</p>
				<div class="read-more cl-effect-14">
					<a href="{% url 'myapp:blogindex' %}" class="more-link">返回</a>
				</div>
			</div>
		</article>
		<!-- 如果空则显示empty下定义的内容 -->
		<!-- empty %}
		<div class="no-post">暂时还没有发布的文章!</div> -->
<!-- 一个页面显示多段，复制多分即可 -->
<!--		<article class="post-1">
			<header>
				<div class="entry-title">
					<a href="#">ARTICLE 1 (Demo)</a>
				</div>
				<div class="entry-meta">
					<span class="post-category"><a href="#">分类显示1</a></span>
					<span class="post-date"><a href="#"><time datetime="2017-01-01T00:00:00+00:00">2017年1月1日</time></a></span>
					<span class="post-author"><a href="#">作者</a></span>
					<span class="comments-link"><a href="#">分类显示2</a></span>
				</div>
			</header>
			<div class="entry-content clearfix">
				<p>一篇好的内容摘要往往能反映一本书或者一篇文章的内涵和精神实质，是本书或文章的灵魂。读者通过阅读内容摘要可以窥一斑而知全貌，了解该内容是否适合自己的需要以及反映的问题。</p>
				<div class="read-more cl-effect-14">
					<a href="#" class="more-link">动作1</a>
				</div>
			</div>
		</article> -->
		<!-- <section>
			<hr>
			<h3>发表评论</h3>
			<form action="#" method="post" class="comment-form">
				<div class="row">
					<div class="col-md-4">
						<label for="id_name">名字：</label>
						<input type="text" name="name" id="id_name" placeholder="name" required="required">
					</div>
					<div class="col-md-4">
						<label for="id_email">邮箱：</label>
						<input type="eamil" name="email" id="id_email" placeholder="email" required="required">
					</div>
					<div class="col-md-12">
						<label for="id_comment">评论：</label>
						<textarea name="comment" id="id_comment" required="required"></textarea>
						<button type="submit" class="btn btn-primary">发表</button>
					</div>
				</div>
			</form>
		</section> -->
	</main>
	{% load blog_tags %}
	<aside class="col-md-4">
		<!-- 页面右边分类 -->
		<div class="widget widget-recent-posts">
			<div class="widget-title">最近发布</div>
			{% get_recent_posts as recent_post_list %}
			<ul>
				{% for post in recent_post_list %}
				<!-- <li><a href="#">标题1：test</a></li>
				<li><a href="#">标题2：test</a></li>
				<li><a href="#">标题3：test</a></li> -->
				<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
				{% empty%}
				<li>暂无文章!</li>
				{% endfor %}
			</ul>
		</div>
		<div class="widget widget-recent-posts">
			<div class="widget-title">时间归档</div>
			{% archives as date_list %}
			<ul>
				<!-- <li><a href="#">标题1：test<span class="post-count">(10)</span></a></li>
				<li><a href="#">标题2：test<span class="post-count">(10)</span></a></li>
				<li><a href="#">标题3：test<span class="post-count">(10)</span></a></li> -->
				{% for date in date_list %}
				<li><a href="{% url 'myapp:datearchives' date.year date.month %}">{{ date.year }} - {{ date.month }}</a></li>
				<!-- <li><a href="#">{{ date.year }} - {{ date.month }} - {{ date.day }}</a></li> -->
				{% empty %}
				<li>暂无归档!</li>
				{% endfor %}
			</ul>
		</div>
		<div class="widget widget-recent-posts">
			<div class="widget-title">文章分类</div>
			{% get_categories as category_list %}
			<ul>
				{% for category in category_list %}
				<li><a href="{% url 'myapp:category_archives' category.pk %}">{{ category.name }} <span class="post-count">(10)</span></a></li>
				<!-- <li><a href="#">标题1：test</a></li>
				<li><a href="#">标题2：test</a></li>
				<li><a href="#">标题3：test</a></li> -->
				{% empty %}
				<li>暂无分类!</li>
				{% endfor %}
			</ul>
		</div>
		<!-- 页面右边标签 -->
		<div class="widget widget-tag-cloud">
			<div class="widget-title">标签标题</div>
			<ul>
				<li class=" btn btn-primary"><a href="#">标签1</a></li>
				<li class=" btn btn-primary"><a href="#">标签2</a></li>
				<li class=" btn btn-primary"><a href="#">标签3</a></li>
				<li class=" btn btn-primary"><a href="#">标签4</a></li>
				<li class=" btn btn-primary"><a href="#">标签5</a></li>
			</ul>
		</div>
		<div class="rss">
			<a href="#"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
		</div>
	</aside>
</div>
{% endblock %}