demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='homepage'),
    #url(r'^add/$', views.add, name='add'),
    url(r'^new_add/(\d+)/(\d+)/$', views.add2, name='add2'),
    url(r'^delete/$', views.access_error,),
    url(r'^delete/(\w+)/(\w+)/$', views.hello_delete, name='ddd'),
    url(r'', include('myapp.urls')),
    url(r'', include('services.urls')),
    url(r'^userauth/', include('userauth.urls')),
]

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'myapp'
urlpatterns = [
    url(r'^hello2',views.hello_delete, name='home2'),
    url(r'^hello',views.hello_add, name='home'),
    url(r'^info/$', views.demo, name='info'),
    url(r'^demo/$', views.DemoShowView.as_view(), name='demo'),
    #url(r'^login', views.login, name='loginpage'),
    url(r'^blogindex/$', views.blogindex, name='blogindex'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='datearchives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category_archives'),
]

services/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'services'
urlpatterns = [
    url(r'^url/$',views.UrlView.as_view(), name='url'),
    url(r'^url/(?P<pk>[0-9]+)/$', views.UrlDetailView.as_view(), name='url_detail'),
    url(r'^url/environment/(?P<pk>[0-9]+)/$',views.Environment_typeView.as_view(), name='environment'),
    url(r'^elasticsearchinfo/$', views.ElasticsearchView.as_view(), name='elasticsearchinfo'),
    url(r'^search/$', views.search, name='search'),
]

userauth/urls.py
from django.conf.urls import url, include
#from django.contrib import admin
from . import views
#from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy

app_name = 'userauth'
urlpatterns = [
    #url(r'^login/$',views.user_login, name='login'),
    #url(r'',include('django.contrib.auth.urls')),
    
    # Django 1.11.0
    # login & logout
    #url(r'^login/$',login, name='login'),
    #url(r'^logout/$',logout, name='logout'),
    url('^login/$',auth_views.LoginView.as_view(template_name='userauth/login.html'), name='login'),
    url('^logout/$',auth_views.LogoutView.as_view(template_name='userauth/logged_out.html'), name='logout'),
    # dashboard
    url('^$',views.dashboard, name='dashboard'),
    # change password
    url('^password-change/$',auth_views.PasswordChangeView.as_view(template_name='userauth/password_change_form.html',
    															   success_url=reverse_lazy('userauth:password_change_done')), name='password_change'),
    url('^password-change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='userauth/password_change_done.html'),name='password_change_done'),
    # reset password & restore password urls
    # email address needs to match the user info
    url('^password-reset/$',auth_views.PasswordResetView.as_view(template_name='userauth/password_reset.html',
    															 email_template_name='userauth/password_reset_email.html', 
    															 subject_template_name='userauth/password_reset_subject.txt',
    															 success_url=reverse_lazy('userauth:password_reset_done')), name='password_reset'),
    url('^password-reset/done/$',auth_views.PasswordResetDoneView.as_view(template_name='userauth/password_reset_done.html'), name='password_reset_done'),
    url('^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.PasswordResetConfirmView.as_view(template_name='userauth/password_reset_confirm.html',
    																												 success_url=reverse_lazy('userauth:password_reset_complete')), name='password_reset_confirm'),
    url('^password-reset/complete/$',auth_views.PasswordResetCompleteView.as_view(template_name='userauth/password_reset_complete.html'), name='password_reset_complete'),
]

templates/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
    <meta name="author" content="">
	<link rel="icon" href="{% static "icon/favicon.ico" %}">
	<title>Demo_Page</title>
	<!-- <link rel="stylesheet" href="./bootstrap-3.3.7/css/bootstrap.min.css"> -->
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/starter-template.css" %}">
	<!-- <link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/foundation.min.css" %}"> -->
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/ie10-viewport-bug-workaround.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/signin.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/sticky-footer-navbar.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/blog.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/highlights/github.css" %}">
	<!-- <link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/dashboard.css" %}"> -->
	<!-- blog -->
	<!-- <link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/custom.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/pace.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/ionicons.min.css" %}"> -->
	<!-- blog end -->
	<!-- <script src="{% static "bootstrap-3.3.7/js/ie-emulation-modes-warning.js" %}"></script>
	<script src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
	<script src="https://cdn.bootcss.com/foundation/5.5.3/js/foundation.min.js"></script> 
	<script src="https://cdn.bootcss.com/foundation/5.5.3/js/vendor/modernizr.js"></script> -->
	<!-- <style>
	.tail{
		position:absolute;
		bottom:1cm;
		width:100%;
		text-align: center;
	}
	.top{
		position:absolute;
		top:1cm;
	/*	width:100%; */
		text-align: center;
	}
	</style> -->
	{% block style %}
	{% endblock %}
</head>
<!--  style="background-color: #fffffb" -->
<body style="background-color: #fff">
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'homepage' %}">Demo</a>
			</div>
			<div id="navbar" class="collapse navbar-collapse">
				{% if request.user.is_authenticated %}
				<ul class="nav navbar-nav">
					<li {% if section == "home" %} class="active" {% endif %}><a href="{% url 'myapp:home' %}">Home</a></li>
					<li {% if section == "url" %} class="active" {% endif %}><a href="{% url 'services:url' %}">URL</a></li>
					<li {% if section == "blog" %} class="active" {% endif %}><a href="{% url 'myapp:blogindex' %}">Blog</a></li>
					{% block nav %}
					{% endblock %}
				</ul>
				{% endif %}
				<ul class="nav navbar-nav navbar-right">
					{% if request.user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ request.user.first_name }} <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="/admin" target="_blank">Admin Page</a></li>
							<li><a href="{% url 'userauth:dashboard' %}">Dashboard</a></li>
							{% if request.user.is_superuser %}
							<li><a href="{% url 'myapp:info' %}">Information Page<span class="sr-only">(current)</span></a></li>
							{% endif %}
							<li><a href="{% url 'myapp:demo' %}">Demo Page<span class="sr-only">(current)</span></a></li>
							<li role="separator" class="divider"></li>
							<li class="dropdown-header">action</li>
							<li><a href="{% url 'userauth:password_change' %}">Change Password<span class="sr-only">(current)</span></a></li>
							<li><a href="{% url 'userauth:logout' %}">Logout<span class="sr-only">(current)</span></a></li>

						</ul>
					</li>
					{% else %}
					<li><a href="{% url 'userauth:login' %}">Log-in<span class="sr-only">(current)</span></a></li>
					{% endif %}
				</ul>
				<form class="navbar-form navbar-right" method="get" id="searchfrom" role="search" action="{% url 'services:search' %}">
					<input type="text" name="q" class="form-control" placeholder="Search..." required="required">
					<button type="submit" class="btn btn-success">Search</button>
				</form>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
	{% block body %}
	{% endblock %}
	<!-- style="background-color: #cccccc" -->
	<footer class="footer">
		<div class="container">
			<p class="text-muted" style="text-align: center;">2018-03-16 Version 1.3.9</p>
		</div>
	</footer>
	<!-- <div style="position: absolute; bottom: 1cm;text-align: center;">
		<hr style="margin-bottom: 3px;border: none;border-top: 1px dotted #000000; height: 1px; width: 100%;">
		<div style="padding-top: -1px;text-align: center;">copyright@ Citsamex 2017-07-18</div>
	</div> -->

	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static "jquery-3.2.1/jquery-3.2.1.min.js" %}"></script>
	<script src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
</body>
</html>

templates/hello.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container" style="margin-top: -80px;">
	<div class="page-header" style="text-align: center;font-size: 20px">{{ hello }}</div>
	<!-- <hr style="background-color: #000000; height: 1px; width: 100%"> -->
	<form class="form-signin" style="text-align: center;" action="/hello" method="post">
		<div style="font-size: 20px;text-align: center;">AAA</div>
		<label for="inputusername" class="sr-only">username</label>
		<input class="form-control" style="height: 30px;" type="text" name="username" id="inputusername" placeholder="username">
		<label for="inputpassword" class="sr-only">password</label>
		<input class="form-control" style="height: 30px;" type="password" name="password" id="inputpassword" placeholder="password">
		<input type="submit" name="add" value="AAA">
	</form>
	<hr style="background-color: #000000; height: 1px; width: 100%">
	<table border="1px" width="50%" style="margin: auto;">
		<thead>
			<th>table1</th>
			<th>table2</th>
			<th width="1%">action</th>
		</thead>
		<tbody>
			{% for line in hellodata %}
			<tr>
				<td>{{ line.user }}</td>
				<td>{{ line.pwd }}</td>
				<td><form action="{% url 'ddd' line.user line.pwd %}" method="post">
						<input class="btn btn-primary" style="padding: 2px 3px;border-radius: 6px;margin: 3px 5px; font-size: 10px" name="delete" type="submit" name="delete" value="BBB">
					</form>
				</td>
			</tr>
			{% endfor %}
			<!-- <tr>
				<td>test1</td>
				<td>test2</td>
				<td><button class="btn btn-primary" style="padding: 2px 3px;border-radius: 6px;margin: 3px 5px; font-size: 10px">AAA</button></td>
			</tr> -->
		</tbody>
	</table>	
</div>
{% endblock %}

templates/hello2.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container" style="margin-top: -30px">
	<!-- <div class="starter-template" style="text-align: left;font-size: 20px"> -->
		<!-- <div style="text-align: left;"> -->
			<div>{{ item }}</div>
			<div><a href="{% url 'myapp:home' %}">click to back.</a></div>
			<div style="margin-top: 100px">this is a test.</div>
			<div><a href="{% url 'ddd' "hunter" "None"%}">hunter</a></div>
			<div><a href="{% url 'add2' 4 5 %}">calc 4+5</a></div>
			<span>123</span>
			<span>456</span>
		<!-- </div> -->
		<!-- <div><button class="btn btn-primary" style="border-radius: 8px">AAA</button></div> -->
	<!-- </div> -->
	<hr style="background-color: #000000; height: 1px; width: 100%">
</div>
{% endblock %}

templates/homepage.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>{{ welcome }}</h1>
	</div>
	<p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with<code>padding-top: 60px;</code>.</p>
</div>
{% endblock %}

templates/infopage.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Demo Page</h1>
	</div>
	<p class="lead">This ia Demo Page.</p>
	<p class="lead">request:{{ request }}</p>
	<p class="lead">resolver_match:{{ request.resolver_match }}</p>
	<table border="2px" width="80%" style="table-layout: fixed; word-wrap: break-word;">
		<thead>
			<th>Attributes</th>
			<th>return value</th>
		</thead>
		<tr>
			<td>request.get_host</td>
			<td>{{ request.get_host }}</td>		
		</tr>
		<tr>
			<td>request.path</td>
			<td>{{ request.path }}</td>		
		</tr>
		<tr>
			<td>request.method</td>
			<td>{{ request.method }}</td>
		</tr>
		<tr>
			<td>request.GET</td>
			<td>{{ request.GET }}</td>
		</tr>
		<tr>
			<td>request.POST</td>
			<td>{{ request.POST }}</td>
		</tr>
		<tr>
			<td>request.content_type</td>
			<td>{{ request.content_type }}</td>
		</tr>
		<tr>
			<td>request.COOKIES</td>
			<td>{{ request.COOKIES }}</td>
		</tr>
		<tr>
			<td>request.is_secure(SSL)</td>
			<td>{{ request.is_secure }}</td>
		</tr>
	</table>
	<p class="lead">{{ request.resolver_match }}</p>
</div>
{% endblock %}

templates/login.html
{%load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
    <meta name="author" content="">
	<link rel="icon" href="http://v3.bootcss.com/favicon.ico">
	<title>Demo_Page</title>
	<!-- <link rel="stylesheet" href="./bootstrap-3.3.7/css/bootstrap.min.css"> -->
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
	<!-- <link rel="stylesheet" href="https://cdn.bootcss.com/foundation/5.5.3/css/foundation.min.css"> -->
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/ie10-viewport-bug-workaround.css" %}">
	<link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/signin.css" %}">
	<script src="{% static "bootstrap-3.3.7/js/ie-emulation-modes-warning.js" %}"></script>
	<script src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
	<!-- <script src="https://cdn.bootcss.com/foundation/5.5.3/js/foundation.min.js"></script> 
	<script src="https://cdn.bootcss.com/foundation/5.5.3/js/vendor/modernizr.js"></script> -->
	<style>
	.tail{
		position:absolute;
		bottom:1cm;
		width:100%;
		text-align: center;
	}
	.top{
		position:absolute;
		top:1cm;
		width:100%;
		text-align: center;
	}
	</style>
</head>
<body>
	<div class="container">
	<!-- <div class="row"> -->
		<!-- <div class="small-5 columns"> -->
			<form class="form-signin" >
				<center><h3 class="form-signin-heading">System Login</h3></center>
				<label for="inputLoginID" class="sr-only">User ID</label>
				<input type="text" id="inputLoginID" class="form-control" placeholder="User ID" required autofocus>
				<label for="inputPassword" class="sr-only">Password</label>
				<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
				<div class="checkbox">
					<label>
						<input type="checkbox" value="remember-me">Remember Me
					</label>
				</div>
				<button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>	
			</form>
		<!-- </div> -->
	<!-- </div> -->
	</div>
	<div class="tail">copyright@ Citsamex 2017-07-18</div>
	<!-- <script src="http://v3.bootcss.com/assets/js/ie10-viewport-bug-workaround.js"></script> -->
</body>
</html>

templates/login2.html
{% extends "base.html" %}

{% block nav %}
<li><a href="{% url 'myapp:home' %}">Home</a></li>
<li><a href="{% url 'services:url' %}">URL</a></li>
<li><a href="{% url 'myapp:blogindex' %}">Blog</a></li>
{% endblock %}

{% block body %}
<div class="container">
	<form class="form-signin" style="text-align: center;" action="/test/" method="post">
		<div style="font-size: 20px;text-align: center;">AAA</div>
		<label for="inputusername" class="sr-only">username</label>
		<input class="form-control" style="height: 30px;" type="text" name="username" id="inputusername" placeholder="username">
		<label for="inputpassword" class="sr-only">password</label>
		<input class="form-control" style="height: 30px;" type="password" name="password" id="inputpassword" placeholder="password">
		<input type="submit" name="submit">
	</form>
	<!--<hr style="background-color: #000000; height: 1px" />
	<div style="text-align: center;font-size: 20px; padding-bottom: 10px">BBB</div>
	<table border="1px" width="50%" style="margin: auto;">
		<thead>
			<th>username</th>
			<th>password</th>
		</thead>
		<tbody>
			{% for line in userdata %}
			<tr>
				<td>{{ line.user }}</td>
				<td>{{ line.pwd }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table> -->
	<!-- <script type="text/javascript" src="/static/jquery-3.2.1/jquery-3.2.1.js"></script> -->
</div>
{% endblock %}

templates/login3.html
{% extends "base.html" %}

{% block nav %}
<li  class="active"><a href="#">Login</a></li>
{% endblock %}

{% block body %}
<div class="container">
	<form class="form-signin" style="text-align: center;" action="/test/" method="post">
		<div style="font-size: 20px;text-align: center;">AAA</div>
		<label for="inputusername" class="sr-only">username</label>
		<input class="form-control" style="height: 30px;" type="text" name="username" id="inputusername" placeholder="username">
		<label for="inputpassword" class="sr-only">password</label>
		<input class="form-control" style="height: 30px;" type="password" name="password" id="inputpassword" placeholder="password">
		<input type="submit" name="submit">
	</form>
	<hr style="background-color: #000000; height: 1px" />
	<div style="text-align: center;font-size: 20px; padding-bottom: 10px">BBB</div>
	<table border="1px" width="50%" align="center" >
		<thead>
			<th>username</th>
			<th>password</th>
		</thead>
		<tbody>
			{% for line in data %}
			<tr>
				<td>{{ line.user }}</td>
				<td>{{ line.pwd }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<!-- <script type="text/javascript" src="/static/jquery-3.2.1/jquery-3.2.1.js"></script> -->
</div>
{% endblock %}

templates/start.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="./bootstrap-3.3.7/icon/favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="./bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="./bootstrap-3.3.7/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="./bootstrap-3.3.7/css/starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="./bootstrap-3.3.7/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/temp.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>{{ title }}</h1>
	</div>
	<p class="lead">{{ now }}</p>
	<p class="lead">{{ section }} - {{ viewname }}</p>
	<p class="lead">{{ elasticsearch_node_info_fs.total.total_in_bytes }}</p>
	<h2 style="padding-bottom: 10px; border-bottom: 1px solid #eee;">Section title</h2>
	<div class="table-responsive">
		<table class="table table-striped">
        	<thead>
            	<tr>
                	<th>Env</th>
                	<th>IP</th>
                	<th>Count</th>
                	<th>CPU</th>
                	<th>Disk</th>
                	<th>JDK</th>
                	<th>Status</th>
                </tr>
            </thead>
            <tbody>
            	<tr>
            		<td>{{ elasticsearch_info.cluster_name }}</td>
            		<td>10.181.57.57</td>
            		<td>{{ elasticsearch_info.indices.count }}</td>
            		<td style="color: #008B45;">{{ elasticsearch_node_info_cpu.cpu.percent }}%</td>
            		<td>{{ elasticsearch_node_info_fs.total.available_in_bytes }}G / {{ elasticsearch_node_info_fs.total.total_in_bytes }}G</td>
            		<td>{{ elasticsearch_info.nodes.jvm.versions.0.version }}</td>
            		{% if elasticsearch_info.status == "green" %}
            		<td style="background-color: #C1FFC1;">UP</td>
            		{% elif elasticsearch_info.status == "yellow" %}
            		<td style="background-color: #fef4a4;">Warn</td>
            		{% elif elasticsearch_info.status == "red" %}
            		<td style="background-color: #CD5C5C;">Error</td>
            		{% endif %}
            	</tr>
            	</tr>
            	<tr>
            		<td>{{ 26.1678172817 | floatformat:2 }}</td>
            		<td>{% widthratio 5 100 1 %}</td>
            		<td>app0</td>
            		<td>app1</td>
            		<td>app2</td>
            		<td>app3</td>
            		<td style="background-color: #CD5C5C;">app4</td>
            </tbody>
        </table>
    </div>

	<!-- <form class="form-signin" style="max-width: 490px; margin-left: 0; padding: 0px;" action="." method="post">
		<label class="sr-only" for="id_new_password1">New password:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="new_password1" id="id_new_password1" required="required" placeholder="New Password" autofocus="autofocus">
		<div>
			<ul>
				<li>Your password cannot be too similar to your other personal information.</li>
				<li>Your password must contain at least 8 characters.</li>
				<li>Your password cannot be a commonly used password.</li>
				<li>Your password cannot be entirely numeric.</li>
			</ul>
		</div>
		<label class="sr-only" for="id_new_password2">New password confirmation:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="new_password2" id="id_new_password2" required="required" placeholder="New Password confirmation">
		{% csrf_token %}
		<p><input class="btn btn-lg btn-primary btn-block" type="submit" name="reset_password" value="Confirm"></p>
	</form> -->
</div>
{% endblock %}