demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='homepage'),
    #url(r'^add/$', views.add, name='add'),
    url(r'^new_add/(\d+)/(\d+)/$', views.add2, name='add2'),
    url(r'^delete/$', views.access_error,),
    url(r'^delete/(\w+)/(\w+)/$', views.hello_delete, name='ddd'),
    url(r'', include('myapp.urls')),
    url(r'', include('services.urls')),
    url(r'^userauth/', include('userauth.urls')),
]

userauth/urls.py
from django.conf.urls import url, include
#from django.contrib import admin
from . import views
#from django.contrib.auth.views import login, logout, password_change, password_change_done, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy

app_name = 'userauth'
urlpatterns = [
    #url(r'^login/$',views.user_login, name='login'),
    #url(r'',include('django.contrib.auth.urls')),
    
    # Django 1.11.0
    # login & logout
    #url(r'^login/$',login, name='login'),
    #url(r'^logout/$',logout, name='logout'),
    url('^login/$',auth_views.LoginView.as_view(template_name='userauth/login.html'), name='login'),
    url('^logout/$',auth_views.LogoutView.as_view(template_name='userauth/logged_out.html'), name='logout'),
    # dashboard
    url('^$',views.dashboard, name='dashboard'),
    # change password
    url('^password-change/$',auth_views.PasswordChangeView.as_view(template_name='userauth/password_change_form.html',
    															   success_url=reverse_lazy('userauth:password_change_done')), name='password_change'),
    url('^password-change/done/$',auth_views.PasswordChangeDoneView.as_view(template_name='userauth/password_change_done.html'),name='password_change_done'),
    # reset password & restore password urls
    # email address needs to match the user info
    url('^password-reset/$',auth_views.PasswordResetView.as_view(template_name='userauth/password_reset.html',
    															 email_template_name='userauth/password_reset_email.html', 
    															 subject_template_name='userauth/password_reset_subject.txt',
    															 success_url=reverse_lazy('userauth:password_reset_done')), name='password_reset'),
    url('^password-reset/done/$',auth_views.PasswordResetDoneView.as_view(template_name='userauth/password_reset_done.html'), name='password_reset_done'),
    url('^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.PasswordResetConfirmView.as_view(template_name='userauth/password_reset_confirm.html',
    																												 success_url=reverse_lazy('userauth:password_reset_complete')), name='password_reset_confirm'),
    url('^password-reset/complete/$',auth_views.PasswordResetCompleteView.as_view(template_name='userauth/password_reset_complete.html'), name='password_reset_complete'),
]

userauth/models.py
from django.db import models
#from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# Create your models here.

# 这个方法需要删除数据库重新makemigrations
#class CustomUser(AbstractUser):
#	telephone_number = models.CharField(max_length=20, blank=True, verbose_name='手机号码')
	#def __str__(self):
	#	return self.telephone_number

#	class Meta(AbstractUser.Meta):
#			pass

# 扩展现有User模型
class CustomUser(models.Model):
	user = models.OneToOneField(User,
								on_delete=models.CASCADE,
								related_name='customuser')
	telephone_number = models.CharField(max_length=20, blank=True, verbose_name='手机号码')

	class Meta:
		verbose_name = '其他信息'

userauth/forms.py
# -*- coding:UTF-8 -*-

from django import forms

# 使用 PasswordInput 控件来渲染 HTMLinput 元素，包含 type="password" 属性
# django 规定，必须继承自 forms.Form 类或者 forms.ModelForm 类
class  LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

userauth/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.contrib.auth import authenticate, login
from userauth.forms import LoginForm
from django.contrib.auth.decorators import login_required

def user_login(request):
	context_user_login = {}
	if request.method == "POST":
		form = LoginForm(request.POST)
		# 判断是否无效
		# 执行校验器，检查 form 中的数据是否符合定义规则
		if form.is_valid():
			# 如果 form.is_valid() 为True
			# 通过 form.cleaned_data 这个dict来获取数据自动转型
			cd = form.cleaned_data
			# authenticate() 检查用户认证信息，如果用户是正确的则返回一个用户对象
			user = authenticate(username = cd['username'],
								password = cd['password'])
			if user is not None:
				# 使用 is_active 属性来检查用户是否可用
				if user.is_active:
					# login() 将用户设置到当前的会话（session）中
					# 调用login()方法集合用户到会话（session）中然后返回一条成功消息
					login(request, user)
					return HttpResponse('Authenticated successfully')
				else:
					return HttpResponse('Disabled account')
			else:
				return HttpResponse('Invalid login')
	else:
		form = LoginForm()
	context_user_login['form'] = form
	return render(request, 'userauth/login.html',context_user_login)

# login_required 装饰器（decorator）会检查当前用户是否通过认证
# 如果用户通过认证，它会执行装饰的视图（view）
# 如果用户没有通过认证，它会把用户重定向到带有一个名为 next 的 GET 参数的登录 URL，该 GET 参数保存的变量为用户当前尝试访问的页面URL
# 通过这些动作，登录视图（view）会将登录成功的用户重定向到用户登录之前尝试访问过的URL
# 请记住我们在登录模板（template）中的登录表单（form）中添加的隐藏<input>就是为了这个目的。

# 定义了一个section变量。我们会使用该变量来跟踪用户在站点中正在查看的页面
# 多个视图（views）可能会对应相同的section。这是一个简单的方法用来定义每个视图（view）对应的section
@login_required
def dashboard(request):
	return render(request, 'userauth/dashboard.html', {'section': 'dashboard'})

templates/userauth/dashboard.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Dashboard</h1>
	</div>
	<p class="lead">Welcome to your dashboard.</p>
</div>
{% endblock %}

templates/userauth/logged_out.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Logged out</h1>
	</div>
	<p class="lead">You have been successfully logged out. You can <a href="{% url 'userauth:login' %}">log-in</a> again.</p>
</div>
{% endblock %}

templates/userauth/login.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<!-- <div class="page-header">
		<h2>Login Page</h2>
	</div>
	<p class="lead">Please use the following form to login</p> -->
	<!-- 先使用{{ form.as_p }}确定表单id-->
	<!-- 这里使用的表单id为 id_username 和 id_password -->
	<!-- 再重新尝试后发现，只要符合表单的POST方法，id可以任意定义-->
	<form class="form-signin" action="." method="post">
		<!-- 用于防止跨站请求伪造攻击 -->
		{% csrf_token %}
		<div class="form-signin-heading" style="font-size: 24px;text-align: center;">System Login</div>
		<label for="inputusername" class="sr-only">username</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="text" name="username" id="inputusername" placeholder="username" required="required" autofocus>
		<label for="inputpassword" class="sr-only">password</label>
		<input class="form-control" style="height: 40px;border-radius: 6px;" type="password" name="password" id="inputpassword" placeholder="password" required="required">
		<input type="hidden" name="next" value="{{ next }}">
		<input class="btn btn-lg btn-primary btn-block" type="submit" name="submit" value="Log In">
	</form>
	{% if form.errors %}
		<div style="text-align: center;color: red;">
			<p>Username or password error.Please try agin.</p>
		</div>
	{% else %}
		<div style="text-align: center;"><p>Please enter your username and password to log-in.</p></div>
	{% endif %}

	{% if next %}
		{% if request.user.is_authenticated %}
		<div style="text-align: center;"><p>Please enter your username and password to log-in</p></div>
		{% else %}
		<div style="text-align: center;color: red;">
			<p>Your account doesn't have access to this page. </br>To proceed,please login with an account that has access.</p>
		</div>
		{% endif %}
	{% endif %}
	<div style="text-align: center;"><a href="{% url 'userauth:password_reset' %}">Forgotten password?</a></div>
	<!-- <div><p style="text-align: center;">Please enter your username and password to log-in</p></div> -->
	<!-- <form class="form-signin" action="." method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p><input class="btn btn-lg btn-primary btn-block" type="submit" value="Log-in"></p>
	</form> -->

	<!--<hr style="background-color: #000000; height: 1px" />
	<div style="text-align: center;font-size: 20px; padding-bottom: 10px">BBB</div>
	<table border="1px" width="50%" style="margin: auto;">
		<thead>
			<th>username</th>
			<th>password</th>
		</thead>
		<tbody>
			{% for line in userdata %}
			<tr>
				<td>{{ line.user }}</td>
				<td>{{ line.pwd }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table> -->
	<!-- <script type="text/javascript" src="/static/jquery-3.2.1/jquery-3.2.1.js"></script> -->
</div>
{% endblock %}

templates/userauth/password_change_done.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Password changed</h1>
	</div>
	<p class="lead">Your password has been successfully changed. You can <a href="{% url 'userauth:login' %}">log-in</a> again.</p>
</div>
{% endblock %}

templates/userauth/password_change_form.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Change your password</h1>
	</div>
	<p class="lead">Use the form below to change your password.</p>
	<form class="form-signin" style="max-width: 490px; margin-left: 0; padding: 0px;" action="." method="post">
		{% if form.errors %}
		<div style="color: red;">
			<p>Password error.Please try agin.</p>
		</div>
		{% endif %}
		<label for="id_old_password" class="sr-only">Old password:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="old_password" id="id_old_password" placeholder="Old Password" required="required" autofocus>
		<label for="id_new_password1" class="sr-only">New password:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="new_password1" id="id_new_password1" placeholder="New Password" required="required">
		<div>
			<ul>
				<li>Your password can't be too similar to your other personal information.</li>
				<li>Your password must contain at least 8 characters.</li>
				<li>Your password can't be a commonly used password.</li>
				<li>Your password can't be entirely numeric.</li>
			</ul>
		</div>
		<label for="id_new_password2" class="sr-only">New password confirmation:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="new_password2" id="id_new_password2" placeholder="New Password confirmation" required="required">
		<p><input class="btn btn-lg btn-primary btn-block" type="submit" name="change_submit" value="Change"></p>
		{% csrf_token %}
	</form>
</div>
{% endblock %}

templates/userauth/password_reset.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Forgotten your password?</h1>
	</div>
	<p class="lead">Enter your e-mail address to obtain a new password.</p>
	<form class="form-signin" style="/*max-width: 520px;*/ margin-left: 0; padding: 0px;" action="." method="post">
		<!-- {{ form.as_p }} -->
		<label class="sr-only" for="id_email">Email:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="email" name="email" maxlength="254" id="id_email" required="required" autofocus="autofocus" placeholder="E-mail address">
		<p><input class="btn btn-lg btn-primary btn-block" type="submit" name="reset_submit" value="Send E-mail"></p>
		{% csrf_token %}
	</form>
</div>
{% endblock %}

templates/userauth/password_reset_complete.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Password reset successfully</h1>
	</div>
	<p class="lead">Your password has been set successfully. You can <a href="{% url 'userauth:login' %}">re-login</a> now.</p>
</div>
{% endblock %}

templates/userauth/password_reset_confirm.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Reset your password</h1>
	</div>
	{% if validlink %}
	<p class="lead">Please enter your new password and confirm.</p>
	<form class="form-signin" style="max-width: 490px; margin-left: 0; padding: 0px;" action="." method="post">
		<label class="sr-only" for="id_new_password1">New password:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="new_password1" id="id_new_password1" required="required" placeholder="New Password" autofocus="autofocus">
		<div>
			<ul>
				<li>Your password cannot be too similar to your other personal information.</li>
				<li>Your password must contain at least 8 characters.</li>
				<li>Your password cannot be a commonly used password.</li>
				<li>Your password cannot be entirely numeric.</li>
			</ul>
		</div>
		<label class="sr-only" for="id_new_password2">New password confirmation:</label>
		<input class="form-control" style="height: 40px;margin-bottom: 5px;border-radius: 6px;" type="password" name="new_password2" id="id_new_password2" required="required" placeholder="New Password confirmation">
		{% csrf_token %}
		<p><input class="btn btn-lg btn-primary btn-block" type="submit" name="reset_password" value="Confirm"></p>
	</form>	{% else %}
	<p class="lead">The password reset link wae invalid, possibly it has already been used. Please requset a new password reset.</p>
	{% endif %}
</div>
{% endblock %}

templates/userauth/password_reset_done.html
{% extends "base.html" %}

{% block nav %}
{% endblock %}

{% block body %}
<div class="container">
	<div class="page-header">
		<h1>Reset your password</h1>
	</div>
	<p class="lead">The password reset E-mail has been sent, Please have a check.</p>
	<p class="lead">If you don't receive an email, please make sure the E-mail address.Click to <a href="{% url 'userauth:password_reset' %}">return</a>.</p>
</div>
{% endblock %}

templates/userauth/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'userauth:password_reset_confirm' uidb64=uid token=token %}
Your username, in case you have forgotten: {{ user.get_username }}